### ISSUE TITLE
「とりあえず投げる先」のPrometheusを決める

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/observability#1]
CFPの募集を、2021/12/09あたりに開始する予定なため、とりあえずデータを投げる先としてPrometheusを決める。
なお、これはあくまでもデータの収集を優先するためであり、データの公開については別途考えるので今回は考慮しない。

**Comment by TakumaNakagame** [comment]
とりあえずDkの環境にすでに構築済みのPrometheusに投げるのが良さそう？

**Comment by oke-py** [comment]
予算や管理の都合上、Observabilityチーム独自のPrometheus（Grafanaなども）は持たない。
