### ISSUE TITLE
参加登録者数の推移と最新値をダッシュボードに表示する

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/observability#17]
### What we want:

<img width="752" alt="users" src="https://user-images.githubusercontent.com/4710215/147378533-a467c12b-518f-45d6-80da-0bac0c5e9754.png">

### How we do it:

It's unclear. We need discussion.

CFPダッシュボードと同じ仕組みでよいかもしれませんが、参加登録者数分のメトリクスができるのは冗長な気がします。
exporterで集計値を出力するのがよいと考えます。
```
# sample
registrants_count 1000
```

**Comment by oke-py** [comment]
@iaoiui 推移の折れ線グラフはダッシュボードに追加できましたね。最新の数値のみのパネルいります？

**Comment by iaoiui** [comment]
確かに最新値漏れてました
作ってみます

**Comment by iaoiui** [comment]
参加者登録数の最新値に加えて、チャット数、視聴者数も最新値を表示する様に変更します
![image](https://user-images.githubusercontent.com/6523614/156880689-f3e1e90f-da96-4a52-be9b-4be64f5a9c7a.png)
