### ISSUE TITLE
同時視聴者数の推移と最新値をダッシュボードに表示する

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/observability#21]
### What we want:

It's unclear. We need discussion.

![viewer](https://user-images.githubusercontent.com/4710215/147536367-7d904164-b44b-4361-bb82-094f897689e1.jpg)

- セッションごとの視聴者数
- セッションごとの視聴者数推移
- セッションごとの視聴率（視聴者数 / 事前登録数？）

### How we do it:

CNDT2021では、毎秒IVSのAPIをたたいて視聴数を取得し、視聴画面に表示していた。詳しいのは jacopen

* https://github.com/cloudnativedaysjp/dreamkast/blob/main/lib/tasks/get_and_save_current_attendees.rake
* https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/production/main/viewer-count.yaml

推移は、IVSのCloudWatchダッシュボードがあるらしい。詳しいのは inductor

**Comment by sharasoujyu** [comment]
セッションごとの視聴者数とその属性について、
モバイル/PC/その他の試聴端末のデータを取得する案もあり。(miroより)

**Comment by sharasoujyu** [comment]
人の動きと流れを確認したい
試聴継続・離脱の傾向について確認したい(miroより)

**Comment by iaoiui** [comment]
一旦Privateダッシュボードで実装して検証し、次回のスピーカー募集時にセッション同時視聴者数の可否の選択オプションがあるとよい
