### ISSUE TITLE
github.com/cloudnativedaysjp/* のコミット数推移を計測する

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/observability#24]
### What we want:

It's unclear. We need discussion.

### How we do it:

It's unclear. We need discussion.

**Comment by mhoshi-vm** [comment]
限定的ではあるが、とれてはいるにいる。
https://grafana.cloudnativedays.jp/explore?orgId=1&left=%5B%22now-3h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22github_repository_open_issues%7B%7D%22%7D%5D

ただ、telegrafがこの辺りの取得がイマイチなので、がんばってExporterを書くのもあり？

**Comment by b1gb4by** [comment]
現段階での必要性がないため一旦クローズします。
