### ISSUE TITLE
デプロイ頻度を計測する

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/observability#25]
### What we want:

It's unclear. We need discussion.

### How we do it:

It's unclear. We need discussion.

**Comment by ryojsb** [comment]
こちらで、Argo CDの可視化が可能。
https://grafana.com/grafana/dashboards/14584

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36046682/147657691-6fbd2fca-14e3-42a5-ab42-33ab486c1bb6.png">

Argo Dashboard
https://grafana.dev.cloudnativedays.jp/d/qPkgGHg7k/argocd?orgId=1

**Comment by mhoshi-vm** [comment]
あと、GithubのIssueなどは、Telegrafからすでに計測しています。

https://grafana.cloudnativedays.jp/explore?orgId=1&left=%5B%22now-3h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22github_repository_open_issues%7B%7D%22%7D%5D

**Comment by b1gb4by** [comment]
ArgoCDとGitHub両方のダッシュボードを作成したのでクローズします。
