### ISSUE TITLE
監視SaaSのスポンサー募集

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#27]
### What we want:

Datadog, NewRelic, Splunk, etc.
監視Saasのスポンサー募集

Observability ハンズオンの実施と関連

It's unclear. We need discussion.

### How we do it:

現在Promotion チームにて確認中のスポンサー募集の件と併せて進める。

**Comment by b1gb4by** [comment]
つかっていいのであれば使うが、Issueとして自分たちの領域ではないのでクローズします。
