### ISSUE TITLE
[会議時相談要]SLI,SLA,SLO の定義について

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#28]
### What we want:

SLI,SLA,SLO の定義について相談が必要

#### 検討対象項目
- 申込者数
- 配信のドロップ率
- 動画配信Uptime
- WebサーバーUptime
- スピーカーの締め切り提出率
- コスト

(issueを分ける必要がある場合は、別途立てる)

### How we do it:

定義については会議時に要相談

あわせて
SLAダッシュボードの作成について相談

**Comment by b1gb4by** [comment]
一旦クローズします。
