### ISSUE TITLE
公式Twitterへの反応数、ハッシュタグツイートの数を取得しダッシュボードに表示する

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#31]
### What we want:

It's unclear. We need discussion.

### How we do it:

Twitter API にてGETする

### Anything else:

[要相談]
現在、PromothionチームにてSocialDogを使用しており、
本項目については、SocialDog上にて表示可能&csv出力可能(キーワードモニタリング機能を使用)
別途、GrafanaのダッシュボードもTwitterAPIを使用して表示するか要相談。

**Comment by mhoshi-vm** [comment]
#15 で対応中です。

**Comment by mhoshi-vm** [comment]
ちなみに SocialDog をPrometheus連携はググっても見つからなかったので、カスタムエクスポーターを Spring Boot でちょこちょこ描いています。
https://github.com/mhoshi-vm/social-analysis

**Comment by mhoshi-vm** [comment]
いろいろ重複しているのでこれも一旦クローズします。
