### ISSUE TITLE
登録者数の見込みとアクション必要かどうか判断するためのダッシュボード

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#33]
### What we want:

登録者数の見込みとアクション必要かどうか判断するためのダッシュボード

### How we do it:

It's unclear. We need discussion.

### Anything else:

(どちらかというとPtomotionの検討課題かもしれません。)

**Comment by b1gb4by** [comment]
ダッシュボードの作成としては現在、必要性が低いためクローズします。
