### ISSUE TITLE
IaaSコスト遷移のダッシュボード作成

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#34]
### What we want:

IaaSコスト遷移のダッシュボード作成

### How we do it:

It's unclear. We need discussion.

**Comment by oke-py** [comment]
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1351 & https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1491 resolved this issue.
