### ISSUE TITLE
スピーカーの動向についてのダッシュボード作成

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#35]
#### スピーカーの動向についてのダッシュボード作成
- スピーカーの動きについて
- 締め切りを守るスピーカーの傾向について

### How we do it:

It's unclear. We need discussion.
(正直なところ、この辺りはどのようなデータを取得して分析すれば良いかまだ思いついていません。)

**Comment by b1gb4by** [comment]
現段階で要望と、必要性があまり感じられないのでクローズします。
