### ISSUE TITLE
ドキュメント化

### ISSUE THREAD

**Issue by iaoiui** [cloudnativedaysjp/observability#41]
### What we want:

現状ObservabilityチームのアウトプットはMiro上やGitHub Issue, PR上、Google Docsにあるが情報が点在している。
また、開発項目に関してもMiro上からIssue登録しているが、各Issueごとの優先度やマイルストーンについて整理がされていない。
そのため、情報の整理と、作業管理の観点でドキュメント化を適宜行っていく。

Observabilityチーム関連のナレッジについても、必要に応じてドキュメントを作成しo11y2022以降の属人化を防止する

現状のドキュメントルートは、[o11y2022のドキュメントルート](https://sites.google.com/view/cnd-mini-march/#h.igt661uweq24)にあるため、今後のカンファレンスで継続的に活動する場合、別途ドキュメントルート相当を作成することが望ましい。

### How we do it:

- [ ] ドキュメント化対象決定
  - [ ] カンファレンスに紐づかない、Observabilityチームの資料類のドキュメントルート
  - [ ] 活動の優先度に関するポリシー #43 
  - [ ] 技術情報
  - [ ] ツール群のアクセス先などオンボーディング関連の内容
    - [ ] 内部向け資料のためPublicリポジトリ以外の場所に別途置く
- [ ] ドキュメント格納先決定
  - [ ] [このリポジトリ](https://github.com/cloudnativedaysjp/observability)を活用したいが、Publicリポジトリのため公開ポリシーを定める必要がある
- [ ] ドキュメントフォーマット決定
  - [x] リポジトリ上で参照しやすいようMarkdownで記載するのが無難
  - [x] フォーマット自体は各ドキュメントに併せて決定する
- [ ] ドキュメント作成

# 現状のObservabilityチームのドキュメントルート内容

[メンバー紹介](https://docs.google.com/document/d/1OhbVollt1dSdFkaEDPLYvirk7hJZJcy41hw-0JlpQbI/edit)
[ミーティング議事録](https://docs.google.com/document/d/1QXT0rKrfEdlDxBxOzfxFkodjixtfEByQScCYjEq35_E/edit#)
[GitHub Projects](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Forgs%2Fcloudnativedaysjp%2Fprojects%2F7%2Fviews%2F1%3Flayout%3Dboard&sa=D&sntz=1&usg=AFQjCNGk0S6SJcb569DEa8EjmeKg3MJSYw)
[何のために、何をとるかのアイデア (miro)](https://www.google.com/url?q=https%3A%2F%2Fmiro.com%2Fapp%2Fboard%2Fo9J_lrK067A%3D%2F&sa=D&sntz=1&usg=AFQjCNHL17cAN9hHMp0kglM7QK3aLQ6x2w)
[アーキテクチャ設計 (miro)](https://www.google.com/url?q=https%3A%2F%2Fmiro.com%2Fapp%2Fboard%2FuXjVOd1SSm0%3D%2F&sa=D&sntz=1&usg=AFQjCNHMOuKL-02JcXccjSCDKDsuO-2hoA)

**Comment by b1gb4by** [comment]
現在、Notionが導入されたのでクローズします。
