### ISSUE TITLE
プレイベントまでのTODO

### ISSUE THREAD

**Issue by iaoiui** [cloudnativedaysjp/observability#45]
### 下記のTODOの消化
- [x] MySQLの移行：@mhoshi-vm
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1451 
- [x] TelegrafのDB向きの変更：@mhoshi-vm
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1384
- [x] GrafanaRole公開：@iaoiui 
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1279
  - [x] https://github.com/cloudnativedaysjp/observability/issues/18
- [x] TwitterDashboard:  @oke-py , @iaoiui 
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1450
- [x] DreamkastExpoerterの完成：@mhoshi-vm
  - [x] https://github.com/cloudnativedaysjp/observability/issues/36
  - [x] https://github.com/cloudnativedaysjp/observability/issues/39
  - [x] https://github.com/cloudnativedaysjp/dreamkast/pull/1144
- [x] DreamkastDasboard: @oke-py , @iaoiui 
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1452
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1512
- [x] LokiExporterの作成: @ryojsb 
  - [x] https://github.com/cloudnativedaysjp/observability/issues/20
- [x] LokiDashboardの完成: @oke-py , @iaoiui 
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1453
- [x] https://github.com/cloudnativedaysjp/observability/issues/46
- [x] 本番向けGrafanaダッシュボードの作成
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1478
- [x] 本番向けダッシュボードのjson更新(一部パネルに変更あるのでdevのjsonをprodに反映する)
- [x] Generalのお掃除
- [x] Twitter スクレイプのintervalを短くする
  - [x] https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1509

**Comment by oke-py** [comment]
Twitter スクレイプのintervalを短くする

**Comment by oke-py** [comment]
Generalのお掃除
