### ISSUE TITLE
Viewer Count のダッシュボード公開可否

### ISSUE THREAD

**Issue by mhoshi-vm** [cloudnativedaysjp/observability#47]
### What we want:

Viewer Count のダッシュボード公開可

### How we do it:

It's unclear. We need discussion.

**Comment by kkmnky** [comment]
@mhoshi-vm 
これってどうなりました？

**Comment by b1gb4by** [comment]
Issueの詳細が曖昧のため、再度ゆうせんどが上がったタイミングでIssueを立てるという事でクローズとします。
