### ISSUE TITLE
Prometheus Backfillingの調査

### ISSUE THREAD

**Issue by iaoiui** [cloudnativedaysjp/observability#5]
過去のメトリクスをPrometheusに取り込む方法を確立することで、後付けでPrometheusを活用することができるため今後活用できるため調査する。
ユースケースとしては、CFPの応募までにExporterが間に合わないが、間に合ったタイミングで過去のメトリクスを手動で生成してPrometheusにimportするといったことが想定される

**Comment by b1gb4by** [comment]
本件のメトリクスは、すでに取得済みのためCloseします
