### ISSUE TITLE
Track Cの視聴者数のカウントが不自然になる

### ISSUE THREAD

**Issue by katzchang** [cloudnativedaysjp/observability#52]
### Current Behavior:
`avg(sum(dreamkast_viewer_count) by(instance,track_id)) by (track_id)` ([Grafana chart](https://grafana.cloudnativedays.jp/explore?left=%5B%221646961071789%22,%221646999229280%22,%22Prometheus%22,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22PBFA97CFB590B2093%22%7D,%22exemplar%22:true,%22expr%22:%22avg(sum(dreamkast_viewer_count)%20by(instance,track_id))%20by%20(track_id)%22,%22interval%22:%22%22,%22refId%22:%22A%22%7D%5D&orgId=1)) でTrack毎の視聴者数を見てみると、`track_id="28"` (Track C)  のメトリクスの挙動が不自然に増えすぎている

`avg(sum(dreamkast_viewer_count) by(instance,track_id, talk_id)) by (track_id, talk_id)` ([Grafana chart](https://grafana.cloudnativedays.jp/explore?left=%5B%221646961071789%22,%221646999229280%22,%22Prometheus%22,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22PBFA97CFB590B2093%22%7D,%22exemplar%22:true,%22expr%22:%22avg(sum(dreamkast_viewer_count)%20by(instance,track_id,%20talk_id))%20by%20(track_id,%20talk_id)%22,%22interval%22:%22%22,%22refId%22:%22A%22%7D%5D&orgId=1))
talk_idを含めたメトリクスでは、Track Cのトークの数値が不自然に横に伸びているものが目立つ。

### Expected Behavior:
各トラック、各トークのリアルタイムの視聴者数に合わせたカウントがされるようにしたい。

### Steps To Reproduce:
上記Grafanaチャートを参照してください。

### Environment:
上記Grafanaチャートを参照してください。

### Anything else:
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/middlewares/dreamkast_exporter.rb
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/models/viewer_count.rb
このあたりを読めばいいのかな、という @oke-py sanのコメントがありました。

Track Cのみの数値に問題があるのか、それとも全体の数値に問題があるのかは確認が必要そうです。

**Comment by kkmnky** [comment]
#1292
で対応し、前回のCNSecで問題ないことを確認したのでクローズ
