### ISSUE TITLE
CNSec用のCFPのダッシュボードを作成する

### ISSUE THREAD

**Issue by b1gb4by** [cloudnativedaysjp/observability#53]
### What we want:

CNSec2022のCFPが開始されたので、o11y同様にCFP登録数の推移と最新値、セッション属性内訳をダッシュボードに表示する

### How we do it:

- [x]  CNSec2022用のCFP Dashboard を作成
- [x] Stagingでの公開
  - [x] [PR](https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1663)
- [x] Productionでの公開
  - [x] [PR]()

**Comment by mhoshi-vm** [comment]
https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1654005328383499
