### ISSUE TITLE
各イベントで計測したドメインメトリクスを長期間参照できるようにしたい

### ISSUE THREAD

**Issue by katzchang** [cloudnativedaysjp/observability#56]
### What we want:
各イベントで計測しているドメインメトリクス（来場者数など）を次回以降のイベントでも紹介するため、参照できるようにしたい。

### How we do it:
Plan A:
Prometheusメトリクスのデータ保持期間を延長したい。
現状は120daysリテンションで、たとえば13ヶ月延長すると約3倍のストレージが必要で、ストレージに余裕があるかは要確認。

Plan B:
イベント毎にPrometheusインスタンスを立ち上げて、データ保持期間を延長しつつ、イベント終了後に塩漬け状態にして、参照させる。
イベントを開催していない時期にメトリクス計測をしないのでストレージにやさしいが、立ち上げたりする手間がかかる。

Plan C:
イベント終了後になんらかの方法でメトリクスをエクスポートし、どこかに保持して、参照できるようにする
形式・手法などは要確認

### Anything else:
メトリクス単位でデータ保持期間を管理できるなら、ストレージ容量をほとんど気にしなくなるはずなんだが、残念ながらPrometheusでは現状それはできない。

**Comment by katzchang** [comment]
設定箇所はここですかね。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/89d43f79923facc799a8755d1470f18f4d028912/manifests/infra/prometheus/overlays/production/prometheus.yaml#L8

**Comment by katzchang** [comment]
過去の議論
https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1265#issuecomment-994661200

**Comment by katzchang** [comment]
> Prometheusのディスク容量ですが、200MB/4h(約1.2GB/1日)くらいの感覚で増えているんですね

現状は150GBの永続化ストレージなので、1.2*120の計算。このペース1年だと450GB必要。
おそらく現状月$40かかっているので、$120になる。

**Comment by katzchang** [comment]
おそらく利用しないだろうメトリクスをドロップする方法があったほうがよさそう。

**Comment by katzchang** [comment]
https://aws.amazon.com/jp/prometheus/pricing/
managed promも検討する価値はある。
データ保持は0.03USD/GB-Monで、延長には優しい。
データ取り込み量を現状のPromで調べる必要はある。

**Comment by sharasoujyu** [comment]
CNSec後にJacopenさんへ相談予定

**Comment by b1gb4by** [comment]
別のIssueで具体的な実装案を考えたため、クローズします。
