### ISSUE TITLE
Prometheus Operator のリファクタリング (リアーキテクチャ?)

### ISSUE THREAD

**Issue by b1gb4by** [cloudnativedaysjp/observability#59]
### What we want:

It's unclear. We need discussion.

- `Prometheus Operator` をリファクタリング (リアーキテクチャ?)する
  - 現状、`Prometheus Operator` はYAMLがベタ書きになっている
  - やりとりは[こちら](https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1656464394577179)

### How we do it:

It's unclear. We need discussion.

- [x] Prometheus Operator の現状を把握する
- [x] Prometheus の構成管理方法見直す
  - Helmで管理するのか？Kustomizeで管理するのか？
  - 現状、保存されているログはどうするのか？

### Anything else:

https://github.com/prometheus-operator/prometheus-operator

**Comment by kkmnky** [comment]
後でkamikenかく

**Comment by kkmnky** [comment]
後でkamikenかく

**Comment by kkmnky** [comment]
#1848 にて対応済みのためクローズ
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1848
