### ISSUE TITLE
set appropriate telegraf interval to gather proposal metrics

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/observability#6]
telegraf executes SQL query every 30 seconds. It seems too much.
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/4a23541fe945be9ee2e639a1becdf027ed45499e/manifests/infra/telegraf/base/configmap.yaml#L30

Determine and modify the interval.
* 1h
* 3h
* 6h
* 1d

**Comment by oke-py** [comment]
globalなintervalの判断材料はまだ足りない。
トラブルシューティング用メトリクスのintervalが1mや5mであると考えると、1h~1dのどれでも誤差の範囲。1hとする。

`inputs.sql` or `inputs.sql.query`ごとに指定する。queryごとに指定できるのか調べるところからやる。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/4a23541fe945be9ee2e639a1becdf027ed45499e/manifests/infra/telegraf/base/configmap.yaml#L92-L103

**Comment by oke-py** [comment]
> interval: How often to gather this metric. Normal plugins use a single global interval, but if one particular input should be run less or more often, you can configure that here. interval can be increased to reduce data-in rate limits.

https://docs.influxdata.com/telegraf/v1.21/administration/configuration/#input-configuration

[SQL Input Plugin](https://github.com/influxdata/telegraf/tree/release-1.21/plugins/inputs/sql)も[GitHub Input Plugin](https://github.com/influxdata/telegraf/tree/release-1.21/plugins/inputs/github)も`interval`という文字列はREADMEにもソースコードにも出てこない。`inputs.sql.query`ごとにはintervalを設定できないかも。まあ、`inputs.sql`に指定すれば十分な気はする。

**Comment by mhoshi-vm** [comment]
@oke-py  さん、すみません、これも反応できておらず、Telegrafですが、inputごとにIntervalを設定する項目ができます。
ただ、これもちょっと伺いたいのですが、なぜTelegraf側を調整していますか？
Telegraf側の頻度をいくら調整しようと、Prometheus側のScrapeの頻度で最終的にデータ格納量が決まりますので、たとえばRDS側の負荷が高いことを回避すること以外大きなメリットはないと思っています。

**Comment by mhoshi-vm** [comment]
AWS側の値段がかわるかな？ともおもいましたが、そんなこともないかと
https://aws.amazon.com/jp/rds/mysql/pricing/?pg=pr&loc=2
> Amazon RDS と Amazon EC2 のインスタンス間のデータ転送は、同一アベイラビリティーゾーン内であれば無料です。

**Comment by iaoiui** [comment]
自分も勘違いしてましたが、確かにPrometheus側のscraping interval側で調整しないといけないですね

**Comment by oke-py** [comment]
RDSのread料金をわかっていなかったので挙げておきました。
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1299 やればRDSを見に行かなくなるので、必要ならcron間隔を修正する必要がありますね。
その必要はなさそうということですね。ありがとうございます。

**Comment by oke-py** [comment]
RDSの料金にも負荷にも影響しないため、30sのままとする。
