### ISSUE TITLE
GitHubにあるIssue数がグラフ表示できるようにする

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#60]
### What we want:

It's unclear. We need discussion.

- GitHubにあるIssue数がグラフ表示できるようにする
参考
[https://github.com/grafana/github-datasource](https://github.com/grafana/github-datasource)

```
grafana/github-datasource
Grafana plugin for fetching stats about issues and pull requests
Stars
123
Language
Go
```

### How we do it:

It's unclear. We need discussion.

**Comment by mhoshi-vm** [comment]
以下のグラフにあるよう現状は 30 分おきのデータになっており、連続した線になっていないので、間のデータを埋める必要があり
https://grafana.cloudnativedays.jp/explore?orgId=1&left=%7B%22datasource%22:%22Prometheus%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22github_repository_open_issues%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D,%7B%22refId%22:%22B%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D

現状はこの行でやっている

https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/infra/telegraf/base/configmap.yaml#L104-L114

これ以上短くすると、たしかGithubのAPI上限にひっかかってしまうのでエージェント側をいじろうとおもうと有償APIアカウントが必要と思われる。

**Comment by hrk091** [comment]
PromQLでsliding windowで集計するようにしたら、間を補完することができました。

```
max by(name)(max_over_time(github_repository_open_issues[1d]))
```

以下のようなグラフが見れます。

![Image](https://user-images.githubusercontent.com/19190276/191139940-ccd2f117-7d54-4adf-b37e-f164322efcea.png)

- 範囲ベクトル関数でsliding windowの集計をしてます
- mysql-o11y再起動時ののDB初期化問題で、telegrafのpodがCrashLoopして値が集計できていない期間があるので、window sizeを1dayにしてます。prodはwindow size小さくても良いと思いますが、そもそも対象がissue数であり細かな動きが見たいものではないと思うので、このままでも良さそうです
- licenseやlanguageがinstrumentation labelとして設定されており、これらが変わっても同じrepositoryは同一のものとして扱いたいので、labelを落としてます。ついでにtelegrafのtarget labelも邪魔なので落として、nameだけ使用しました

**Comment by hrk091** [comment]
これでグラフ表示はできるようになりましたが、ダッシュボードの要件（public/privateのどちらか、こういうコミュニティ活動のメトリクスをどこかに集約したいのか or する予定があるか）などお伺い出来てないので、改めて要件をヒアリングさせてください（金曜定例が良いですかね？）

**Comment by hrk091** [comment]
prodのprivateで閲覧可能になったので、closeします

https://grafana.cloudnativedays.jp/d/anfvkn44k/github?orgId=1
