### ISSUE TITLE
GrafanaダッシュボードにてViewerのPermissionsがViewになっていた件

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/observability#63]
### Current Behavior:

下記slackより
https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1659248874261029

公式アカウントへのDMにてPrivate設定の項目が見えるとのこと。
> いつもカンファレンスを運営いただき、ありがとうございます。 CloudNative Security Conference 2022のgrafana上でDashboard「private」のAWS Billing等、一部のメトリクスが閲覧できる様です。[event.cloudnativedays.jp/cnsec2022/o11y](http://event.cloudnativedays.jp/cnsec2022/o11y) では「閲覧できるのは、“General”, “public” の2つです。」と記載されていましたので、期待していない挙動でなければと思い、ご連絡させていただきました。 開発中の一時的な現象・privateでも一部のメトリクスの閲覧は許容している等の事情もあるかと思いますので、杞憂であればご容赦ください。開催直前でお忙しいかと思いますので、返信もご不要です。

### Expected Behavior:
jacopenさんにて対処済み。
フォルダ全体のViewerのPermissionsがViewになっていてたため設定削除。

原因調査が必要
(Grafana Update時に設定値が変わった？)

**Comment by mhoshi-vm** [comment]
Prometheusとして、Privateとして見せるべきメトリクスはだいぶ絞られてきたので、別Prometheus/Grafanaセットを立てるほうがいいのかもしれない。

**Comment by b1gb4by** [comment]
- 変更したバージョンとの差分を確認したが、大きな変更はなかった
- Dashboardのパーミッションは、YAMLで管理できないっぽい
  - Enterpiseだとできる？
  - アップグレード時に気をつける事項として、対処するしかないかなー
 
https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/
https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/#dashboard-permissions
