### ISSUE TITLE
CNDT2022用のCFPダッシュボードを作成する

### ISSUE THREAD

**Issue by hrk091** [cloudnativedaysjp/observability#68]

**Comment by hrk091** [comment]
進捗
- CNDT2022向けのCFPダッシュボードを、dev環境にてCNSecからコピーして作成（9/6火曜はここまで）
- devのdreamkastにtestdataとしてproposalを登録（計5件）
- moniroting namespace上のcronjobを手動実行し、正常終了を確認
- telegrafのflushが動いていることを確認
- devのgrafanaでproposal数は取れている（ただし、CNDT2022のdev dreamkastからのデータではなさそう）
- 想定受講者数のseed値をCNDT2022向けに変更したが、データが流れてきていない

**Comment by faruryo** [comment]
cndt2022のissueで管理しているようなので、移動しちゃいます
https://github.com/cloudnativedaysjp/cndt2022/issues/39
