### ISSUE TITLE
オフライン会場でのObservabilityコンテンツを開発する

### ISSUE THREAD

**Issue by b1gb4by** [cloudnativedaysjp/observability#72]
### What we want:

It's unclear. We need discussion.

- オフライン会場で実施する、Observabilityのコンテンツの開発を行う
- 開発するものは以下の通り
  - OAK-1を使用した各セッションごとの人数の推移

### How we do it:

It's unclear. We need discussion.

- [x] OAK-1を触る
- [x] OAK-1で読み込ますPythonファイルのソースの理解
- [x] 設計仕様
- [x] 実装
- [x] 検証

**Comment by ureuzy** [comment]
https://github.com/prometheus/client_python#exporting-to-a-pushgateway

**Comment by b1gb4by** [comment]
当日のカメラをどう固定するのか？

**Comment by shukawam** [comment]
Prometheus Push Gateway.
[https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1956](https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1956)
[https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1957](https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1957)

**Comment by hrk091** [comment]
10/6作業で達成したこと（カメラでの人数計測関連）

- devにprometheus pushgatewayを建てる
- https://github.com/luxonis/depthai-experiments/tree/master/gen2-people-counter を参考に、カメラに映る人数をカウントしてpushgatewayに通知するsampleを実装
- pushgatewayをスクレイプし、devのgrafanaでグラフ表示
- raspberry piのセットアップ & depthai sample appが動くことを確認

**Comment by b1gb4by** [comment]
購入をする機材

- microHDMI変換ケーブル × 2
  - ラズパイの画面出力のため
  - https://amzn.asia/d/hX602wg
- カメラ固定スタンド (ゴリラポッド) × 2
  - OAK-1を固定するため
    - 当日は落下防止のため、ワイヤーなども取り付けること
    - https://amzn.asia/d/7RlQ118
- USB (SSD)
  - https://amzn.asia/d/hyBSjYf
- ラズパイのSIMの取り付けるパーツ

**Comment by ureuzy** [comment]
https://github.com/cloudnativedaysjp/observability/issues/77 wordcloud
https://github.com/cloudnativedaysjp/observability/issues/78 people count
https://github.com/cloudnativedaysjp/observability/issues/79  co2 metrics

**Comment by b1gb4by** [comment]
すべての実装を完了したのでクローズします
