### ISSUE TITLE
devのlokiで volume full

### ISSUE THREAD

**Issue by hrk091** [cloudnativedaysjp/observability#76]
devクラスターのlokiでcrash loopが発生。

```
failed to generate container “a2abe1f37582970c6355573e7df8ebac3716da079b2feb03ee0cd56bf03a592f” spec: failed to generate spec: relabel “/var/lib/kubelet/pods/d327b852-5f23-4cfb-8ffa-c3a950988692/volumes/kubernetes.io~csi/pvc-044595a0-cac2-4a98-baea-00506440a9a9/mount” with “system_u:object_r:data_t:s0:c583,c1020” failed: lsetxattr /var/lib/kubelet/pods/d327b852-5f23-4cfb-8ffa-c3a950988692/volumes/kubernetes.io~csi/pvc-044595a0-cac2-4a98-baea-00506440a9a9/mount/loki: no space left on device
```

とのことで、lokiのdata永続化のためのpvcがfullの模様。

devのlokiがmountしているpvcは10Gだが、prodも同じく10Gなので、prodでも出る懸念あり。

### Environment:
- cluster: dev
- argocd-apps: loki

**Comment by hrk091** [comment]
暫定対処として、storageClassに `allowVolumeExpansion` を仕込んでEBSの領域拡張を可能にし、lokiがmountしているpvcを10G -> 20G に変えた所、EBSを20Gに拡張でき、lokiも正常に起動するようになった。

これで数ヶ月はしのげると思うが、
- 今のままデータを貯め続けると数カ月後に再発する
- prodも10Gなので、近々発生しうる

ため、恒久解を考えたい。

恒久解としてぱっと思いつくのは以下
- 今の構成のままで、logの保持期間を定め、rotationするようにする（山本さん情報: サイズができればよいが、期間の指定しかできないっぽい）
- 構成を変えて、boltdb-shipperのbackendとしてs3などを使うようにする

**Comment by b1gb4by** [comment]
`retention`の機能は以下の、`table_manager.retention_period`オプションを使用すると実現できる.

https://github.com/grafana/helm-charts/blob/b3c0de22803adb4a8629ea20842d2aa8ac4f20ec/charts/loki/values.yaml#L105

実装例はこんな感じ

```yaml
table_manager:
  retention_deletes_enabled: true
  retention_period: 24h # <-- TTLを設定する場所
```

**Comment by b1gb4by** [comment]
Lokiをリソースから削除したので、クローズします。
