### ISSUE TITLE
people count実装

### ISSUE THREAD

**Issue by ureuzy** [cloudnativedaysjp/observability#78]
- [x] デモレベルでの動作
- [ ] ラズパイのセットアップで詰まっている（opencvのbuildが終わらない）
- [ ] ラズパイの再セットアップ with SSD (SSH接続できるようにしておく)
- [ ] 長時間動かして、排熱が大丈夫か確認
- [ ] リハーサルで会場で設営してみて、どれくらいの精度になるか・Grafana上でどういう情報提供ができるかを確認
- [ ] prodのpush-gatewayのsetup
- [ ] devのpush-gatewayのTLS対応？
- [ ] 現地メトリクス用のダッシュボードの用意(co2と共有するはず)

**Comment by b1gb4by** [comment]
実装が完了したのでクローズします
