### ISSUE TITLE
co2 metrics実装

### ISSUE THREAD

**Issue by ureuzy** [cloudnativedaysjp/observability#79]
- [x] localへのpush-gatewayの確認
- [x] 現在動いているpush gatewayへ書き換える
- [x] リファクタリング
- [x] リハーサル出れないのでCo2センサをどなたかに託す
- [x]  現地メトリクス用のダッシュボードの用意(people countと共有するはず)

**Comment by b1gb4by** [comment]
実装が完了したのでクローズします
