### ISSUE TITLE
11/6 リハーサル

### ISSUE THREAD

**Issue by b1gb4by** [cloudnativedaysjp/observability#80]
リハーサルまでのあれこれと、リハーサルの振り返りをまとめるissue

**Comment by b1gb4by** [comment]
# 各自の準備するもの

## okamoto

SIM, ラズパイ, モバイルルーター, OAK-1, ゴリラポット, micro HDMIケーブル, USB(OS), USB給電, キーボード

## faru

ラズパイ(kamiken)(micro USB to HDMI、typeC給電)、CO2センサー(kamiken)、無線キーボードマウス(faru)、モバイルディスプレイ(faru)(各種ケーブル、電源タップ(faru)

## Okui

ラズパイ, OAK-1, ゴリラポッド、micro HDMIケーブル、USB給電、無線キーボード

## 上になさそうなもの

電源タップ、電源ケーブル？、ディスプレイ

**Comment by hrk091** [comment]
リハーサルで見つかった課題
- OAK-1は、USBを延長すると動かない（USB3.0/3.1ケーブル単独 1mだと動く）
- raspberry piの画面を表示せずにssh接続だと、アプリが動かない
- A会場で２つのOAK-1を使うので、Grafana側で合成が必要

事務局と要相談
- OAK-1を会場上部に付ける場合は、転落防止の対応が必要
- OAK-1のケーブルを壁に沿わせるところの養生をどうするか

**Comment by hrk091** [comment]
> raspberry piの画面を表示せずにssh接続だと、アプリが動かない

`export DISPLAY=:0.0` を設定すれば、動くようになった

**Comment by hrk091** [comment]
### 残タスク
people-count
- OAK-1を、3m長のUSBケーブルで動作検証
- 10h程度の長安（主に熱問題の計測）
- people-count用のdashboardの作成
  - ２つのOAK-1の出力を合成が必要
- モバイルルータが動くようにする
- 転落防止の方法を決定する
- 養生など当日のセットアップについて決定する
- 資材の追加調達
  - 3m長のUSBケーブルで動作確認できたら、2本購入
  - モバイルディスプレイを最低一つ調達

**Comment by b1gb4by** [comment]
@hrk091 
> OAK-1を、3m長のUSBケーブルで動作検証

ここいかがでした？
