### ISSUE TITLE
CI/CD Conference 2023のCFPダッシュボードを作成・公開する。

### ISSUE THREAD

**Issue by b1gb4by** [cloudnativedaysjp/observability#86]
### What we want:

It's unclear. We need discussion.

### How we do it:

It's unclear. We need discussion.

**Comment by ureuzy** [comment]
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/2239

**Comment by ureuzy** [comment]
- [x] dev
- [x] prd

**Comment by b1gb4by** [comment]
完了したのでクローズします
