### ISSUE TITLE
MySQL ver.8.0でCronJobが正常に動作しない

### ISSUE THREAD

**Issue by b1gb4by** [cloudnativedaysjp/observability#90]
### Current Behavior:

- `mysql-o11y`で使用している、イメージタグを`8.0`にしたところ、正常に動作しなくなった

### Steps To Reproduce:

- [x] 検証・調査
- [x] Dev反映
- [x] Prod反映

### Environment:

- cluster: dev
- argocd-apps: mysql-o11y

### Anything else:

- イメージタグを`8.0`では、パッチバージョンが何なのかが不明で不具合発生時にバージョンの特定に時間がかかるので、パッチバージョンも含めた指定に変更する

**Comment by b1gb4by** [comment]
このバージョンに変更時に、うごかなくなった (と思う)
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-32.html

**Comment by ureuzy** [comment]
> mysqldump バージョン 8.0.32で–single-transactionを使用するには、RELOADまたはFLUSH_TABLES権限のいずれかが必要でした。この要件は、gtid_mode=ON（デフォルト OFF）と–set-gtid-purged = ON|AUTO（デフォルト AUTO）の両方の場合にのみ適用されるようになりました。（バグ #109685、バグ #109701、バグ #34993824、バグ #34998910、バグ #35020512）
参照：この問題はバグ #105761、バグ #33630199のリグレッションです。

現行設定

```
$ mysqldump --single-transaction \
                  --quick \
                  --set-charset \
                  --no-tablespaces \
                  --set-gtid-purged=OFF \
                  -u $RDS_USER -p"$RDS_PASSWORD" -h $RDS_HOST dreamkast \
                  conference_days conferences proposal_item_configs
                  proposal_items \
                  proposals talk_categories talk_difficulties talk_times talks
                  talks_speakers \
                  tracks \
                  > $HOME/rds.dump; \
                  mysql -u $MYSQL_USER -p"$MYSQL_PASSWORD" -h $MYSQL_HOST
                  dreamkast < $HOME/rds.dump
```

8.0.32のパッチで動作しなくなっていたが、8.0.33のパッチで動く

**Comment by ureuzy** [comment]
パッチバージョンまで指定するでFixで良いと思います。

**Comment by b1gb4by** [comment]
解決したのでクローズします
